version: '3.1'
# Use postgres/example user/password credentials

services:

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cov19
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080