# Generated by Django 2.1.1 on 2020-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default='2020-03-22')),
                ('isCovidPositive', models.BooleanField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('hasChills', models.BooleanField(null=True)),
                ('isFeelingWeak', models.BooleanField(null=True)),
                ('hasBodyAches', models.BooleanField(null=True)),
                ('hasContinousCough', models.BooleanField(null=True)),
                ('hasSniff', models.BooleanField(null=True)),
                ('hasDiarrhea', models.BooleanField(null=True)),
                ('hasThroaPain', models.BooleanField(null=True)),
                ('hasHeadache', models.BooleanField(null=True)),
                ('isEasierOutOfBreath', models.BooleanField(null=True)),
                ('wasRiskzoneLastTwoWeeks', models.BooleanField(null=True)),
                ('hadContactLastTwoWeeks', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default='2020-03-22')),
                ('hasDisease', models.BooleanField()),
                ('disease', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('hasMedication', models.BooleanField()),
                ('medication', models.TextField()),
                ('isFluVaccined', models.BooleanField()),
                ('age', models.IntegerField(null=True)),
                ('gender', models.IntegerField(choices=[('1', 'male'), ('2', 'female'), ('3', 'divers')])),
            ],
        ),
    ]
