# Generated by Django 2.1.1 on 2020-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200322_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='hasContinousCough',
            new_name='hasThroatPain',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='hasThroaPain',
        ),
        migrations.AddField(
            model_name='dailydata',
            name='cough',
            field=models.CharField(choices=[('dry', 'dry'), ('produtive', 'productive'), ('none', 'none')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='generalFeeling',
            field=models.CharField(choices=[('critical', 'critical'), ('bad', 'bad'), ('normal', 'normal'), ('good', 'good')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='disease',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('divers', 'divers')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='hasDisease',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='hasMedication',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='isFluVaccined',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='medication',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
