# Generated by Django 3.0.4 on 2020-03-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_covid_positive', models.BooleanField()),
                ('temperature', models.FloatField()),
                ('has_chills', models.BooleanField()),
                ('is_feeling_weak', models.BooleanField()),
                ('has_body_aches', models.BooleanField()),
                ('has_continous_cough', models.BooleanField()),
                ('has_sniff', models.BooleanField()),
                ('has_diarrhea', models.BooleanField()),
                ('has_throat_pain', models.BooleanField()),
                ('has_headache', models.BooleanField()),
                ('is_easier_out_of_breath', models.BooleanField()),
                ('was_riskzone_last_two_weeks', models.BooleanField()),
                ('had_contact_last_two_weeks', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EntryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('has_disease', models.BooleanField()),
                ('disease', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('has_medication', models.BooleanField()),
                ('medication', models.TextField()),
                ('is_flu_vaccined', models.BooleanField()),
                ('age', models.IntegerField(null=True)),
                ('gender', models.IntegerField(choices=[('1', 'male'), ('2', 'female'), ('3', 'divers')])),
            ],
        ),
    ]
