# Generated by Django 3.0.4 on 2020-03-21 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydata',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
